version: "3.8"
services:

  database:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: teste-natura-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@TesteN4tur4"